name: Docker PHP Images build

on:
  push:
    branches:
      - 'main'

jobs:
  build_test_release:
    name: Build, Test & Release
    strategy:
      matrix:
        include:
          - php_version: '8.1'
          - php_version: '8.2'

    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Build and test image
        run: |
          make build PHP_VERSION=${{ matrix.php_version }}
          docker images | grep symfony-cli

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: make tag push TAG="${{ matrix.php_version }}" DOCKERHUB_USERNAME="enabel"

      - name: Release latest
        if: ${{ (github.event_name == 'push' || github.event_name == 'schedule') && matrix.php_version == '8.2' }}
        run: make tag push TAG="latest" DOCKERHUB_USERNAME="enabel"
